version: "3"

networks:
    net:
        driver: bridge

services:
    playwright:
        user: 1000:1000

        build:
            context: ./
            dockerfile: playwright.Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}

        networks:
            - net

        volumes:
            - ./:/app

        environment:
            - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

        working_dir: "/app"
        command: "tox"
